project: default
source:
  repoURL: https://github.com/kdvops/simpleApi.git
  path: k8s
  targetRevision: main
  directory:
    recurse: true
    jsonnet: {}
destination:
  server: https://kubernetes.default.svc
  namespace: kdvops-ns
