apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-mysql
  namespace: simpleapi
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api-mysql
  template:
    metadata:
      labels:
        app: api-mysql
    spec:
      containers:
        - name: api
          image: silencfox/simpleapi:latest
          ports:
            - containerPort: 3000
          env:
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: api-config
                  key: PORT
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: api-config
                  key: DB_HOST
            - name: DB_USER
              valueFrom:
                configMapKeyRef:
                  name: api-config
                  key: DB_USER
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: api-config
                  key: DB_NAME

            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: MYSQL_ROOT_PASSWORD
