apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: api-mysql
  namespace: simpleapi
spec:
  replicas: 2
  revisionHistoryLimit: 5
  selector:
    matchLabels:
      app: api-mysql
  template:
    metadata:
      labels:
        app: api-mysql
    spec:
      containers:
        - name: api
          image: kdvops/api-mysql:latest   # <-- reemplaza si usas otra imagen
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          env:
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: api-config
                  key: PORT
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: api-config
                  key: DB_HOST
            - name: DB_USER
              valueFrom:
                configMapKeyRef:
                  name: api-config
                  key: DB_USER
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: api-config
                  key: DB_NAME
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: MYSQL_ROOT_PASSWORD

  strategy:
    canary:
      steps:
        - setWeight: 20
        - pause: { duration: 30s }
        - setWeight: 50
        - pause: { duration: 30s }
        - pause: {}   # requieres aprobaciÃ³n manual si usas kubectl argo rollouts promote
      trafficRouting:
        # Cambiar si usas NGINX:
        # nginx: {}
        traefik:
          stableSvc: api-service
          # Un preview service opcional
          canarySvc: api-service-preview
