name: Full CI/CD

on:
  push:
    branches: [ "main","dev" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install dependencies
        working-directory: ./App
        run: npm install

      - name: Run Tests
        working-directory: ./App
        run: npm test

      - name: Trivy FS Scan
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: fs
          scan-ref: ./App
          severity: HIGH,CRITICAL
          format: table
          
      - name: Sonar Scan
        if: false
        uses: sonarsource/sonarqube-scan-action@v6
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: "https://sonarcloud.io"

  docker:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t simpleapi:${{ github.sha }} ./App

      # -----------------------------
      # üîê TRIVY Docker Image Scan
      # -----------------------------
      - name: Trivy Image Scan
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: myapp:${{ github.sha }}
          severity: HIGH,CRITICAL
          format: table
          exit-code: 1     # ‚ùó Hace fallar el pipeline si encuentra vulnerabilidades serias
          ignore-unfixed: true

      - name: Login to Docker Hub
        if: false
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push image
        #if: github.ref == 'refs/heads/main'
        if: false
        run: |
          docker tag simpleapi:${{ github.sha }} silencfox/simpleapi:latest
          docker push silencfox/simpleapi:latest
    
  deploy:
    runs-on: ubuntu-latest
    needs: docker
    
    steps:

      - name: Despliegue
        run: echo "tarea de despliegue"

      - name: HashiCorp - Setup Terraform
        # You may pin to the exact commit or the version.
        # uses: hashicorp/setup-terraform@633666f66e0061ca3b725c73b2ec20cd13a8fdd1
        uses: hashicorp/setup-terraform@v2.0.3

      - name: test terraform
        run: terraform init


      
      #- name: Deploy to K8s via kubectl
      #  uses: azure/k8s-deploy@v4
      #  with:
      #    manifests: |
      #      k8s/deployment.yaml
      #    images: |
      #      mydocker/myapp:${{ github.sha }}
      #    namespace: production
      #  env:
      #    KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG }}


